### ISSUE TITLE
[BUG] Segmentation Fault

### ISSUE THREAD

**Issue by ampf27** [BC-SECURITY/Starkiller#64]
**Empire Version**
- Empire 3.8.2

**Starkiller Version**
1.7

**OS Information (Linux flavor, Python version)**
- OS:  Kali 2020.4
- Python: 3.9.2

**Describe the bug**

Empire and deathstar (I'm aware it's not yours but if you could help)

**To Reproduce**

I run the commands

```
powershell-empire --rest --username "username" --password "password"

deathstar --username "username" --password "password"
```

and both are working, but when I open starkiller both close automaticaly and do not run while starkiller is open

I have installed starkiller through

`apt install starkiller
`

this is what I get on empire when I run starkiller

`zsh: segmentation fault powershell-empire --rest --username empireadmin --password password123
`

and this is what I get on deathstar when I run starkiller

```
Traceback (most recent call last):
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpcore/_async/connection.py", line 93, in arequest
    self.socket = await self._open_socket(timeout)
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpcore/_async/connection.py", line 119, in _open_socket
    return await self.backend.open_tcp_stream(
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpcore/_backends/asyncio.py", line 270, in open_tcp_stream
    return SocketStream(
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [Errno 111] Connect call failed ('127.0.0.1', 1337)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/bin/deathstar", line 8, in <module>
    sys.exit(run())
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/deathstar/deathstar.py", line 385, in run
    asyncio.run(main(args))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/deathstar/deathstar.py", line 352, in main
    await deathstar.power_up()
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/deathstar/deathstar.py", line 334, in power_up
    await asyncio.gather(*[
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/deathstar/deathstar.py", line 273, in agent_spawner
    lambda c: c.credtype == "plaintext", await self.empire.credentials.get()
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/deathstar/empire.py", line 184, in get
    r = await self.client.get("creds")
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpx/_client.py", line 1548, in get
    return await self.request(
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpx/_client.py", line 1371, in request
    response = await self.send(
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpx/_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpx/_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.9/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectError: [Errno 111] Connect call failed ('127.0.0.1', 1337)
```

**Expected behavior**

I was expecting to be able to access to the deathstar listener on starkiller

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

What can be the reason for these errors?

Thank you in advance

**Comment by vinnybod** [comment]
Reopening. Thanks for providing a lot of detail. In the future, leave all the section headers, even if you leave them blank. The bot is sensitive like that.

**Comment by ampf27** [comment]
Thank you for clarifying about how to post an issue and for reopening the
issue too

**Comment by vinnybod** [comment]
Sorry I have not had time to really dig into this yet, but people on our Discord with the same problem were able to solve it with these commands

```
sudo apt update && sudo apt -y full-upgrade
```
